Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - spec/spec_helper.rb
    - vendor/**/*
  NewCops: enable